name: Publish Rust Crate

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Verify build
        run: cargo build --release

      - name: Run tests
        run: cargo test --release

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO }}
        run: cargo publish --token $CARGO_REGISTRY_TOKEN
